# Generated by Django 5.1.2 on 2024-12-02 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('idProductos', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=30)),
                ('precio', models.FloatField()),
                ('stock', models.CharField(max_length=100)),
                ('fechaCaducidad', models.DateField()),
                ('descripcion', models.CharField(max_length=100)),
                ('idSucursal', models.PositiveIntegerField()),
                ('idProveedor', models.PositiveIntegerField()),
            ],
        ),
    ]
