# Generated by Django 5.1.2 on 2024-12-02 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('idVenta', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fechaVenta', models.DateField()),
                ('total', models.FloatField()),
                ('idCliente', models.PositiveIntegerField()),
                ('idEmpleado', models.PositiveIntegerField()),
                ('tipoPago', models.CharField(max_length=20)),
                ('descuento', models.FloatField()),
                ('idProducto', models.PositiveIntegerField()),
                ('cantidad', models.CharField(max_length=500)),
            ],
        ),
    ]
